### ISSUE TITLE
Bug: Panic while trying to paste a multiline command into the shell

### ISSUE THREAD

**Issue by henil** [mosaic-org/mosaic#100]
Continuing from #93 

Steps to reproduce:
Trying to paste this multiline command into fish shell causes a panic.

```fish
echo -ne (\
        df -l -h | grep -E 'dev/(xvda|sd|mapper)' | \
        awk '{printf "\\\\t%s\\\\t%4s / %4s  %s\\\\n\n", $6, $3, $2, $5}' | \
        sed -e 's/^\(.*\([8][5-9]\|[9][0-9]\)%.*\)$/\\\\e[0;31m\1\\\\e[0m/' -e 's/^\(.*\([7][5-9]\|[8][0-4]\)%.*\)$/\\\\e[0;33m\1\\\\e[0m/' | \
        paste -sd ''\
    )
```
With error:
>  Error: thread 'screen' panicked at 'swap_remove index (is 36) should be < len (is 1)': library/alloc/src/vec.rs:979

I don't think the issue is with escaping the newline character, because I have tried other simple multiline `echo` command and it seems to work properly.

**Comment by imsnif** [comment]
@henil - I can't reproduce this. There are some compatibility fixes in main though, can you pull the latest and see if by any chance this fixes it for you?

**Comment by henil** [comment]
Still the same.

Attaching the whole stack trace, maybe this could help find the issue?
```
Originating Thread(s):
1. stream_terminal_bytes: AsyncTask
2. screen_thread: HandlePtyEvent

Error: thread 'screen' panicked at 'swap_remove index (is 36) should be < len (is 1)': library/alloc/src/vec.rs:979
   0: mosaic::errors::handle_panic
             at src/errors.rs:15:21
   1: mosaic::start::{{closure}}
             at src/main.rs:186:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
   5: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
   6: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85:14
   7: alloc::vec::Vec<T>::swap_remove::assert_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:979:13
   8: alloc::vec::Vec<T>::swap_remove
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:984:13
   9: mosaic::terminal_pane::scroll::WrappedFragment::add_character
             at src/terminal_pane/scroll.rs:231:13
  10: mosaic::terminal_pane::scroll::Scroll::add_character
             at src/terminal_pane/scroll.rs:388:13
  11: <mosaic::terminal_pane::terminal_pane::TerminalPane as vte::Perform>::print
             at src/terminal_pane/terminal_pane.rs:362:9
  12: mosaic::terminal_pane::terminal_pane::TerminalPane::handle_event
             at src/terminal_pane/terminal_pane.rs:101:17
  13: mosaic::screen::Screen::handle_pty_event
             at src/screen.rs:395:13
  14: mosaic::start::{{closure}}
             at src/main.rs:248:29
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
  16: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464:17
  17: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308:9
  18: std::panicking::try::do_call
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
  19: __rust_try
  20: std::panicking::try
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
  21: std::panic::catch_unwind
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382:14
  22: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463:30
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/panda/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
  25: start_thread
  26: __GI___clone
```

**Comment by imsnif** [comment]
I already know where it is. Just not sure why it happens. :(

It happens with just one pane, right? Is it different if the terminal window size is big or small? Like, if you expand it to the full screen, does it still happen?

**Comment by henil** [comment]
Right, trying this in fullscreen not cause panic.

Maybe this is related to #106 because shortening the `sed` command also fixes the issue.

**Comment by imsnif** [comment]
> Right, trying this in fullscreen not cause panic.
> 
> Maybe this is related to #106 because shortening the `sed` command also fixes the issue.

That's what I thought - but we just fixed it in main...

**Comment by henil** [comment]
Can you try `cat`ing this log file, to see if this causes panic for you?

[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5710787/mosaic-3.log)

**Comment by imsnif** [comment]
Sure, but let's make sure I have the same size terminal window.
Could you find out yours by doing:
`tput lines` and `tput cols`?

**Comment by henil** [comment]
```bash
> tput lines
36
> tput cols
149
```

**Comment by imsnif** [comment]
Okay, reproduced it with cat and this terminal size! Good call :)
Debugging this now. Thanks!

**Comment by imsnif** [comment]
@henil - I just merged a fix for this. Could you please confirm?

**Comment by henil** [comment]
Thanks, It's fixed!
