### ISSUE TITLE
Panic: cursor out of bounds

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#106]
I'm not sure what's causing the panic, but it happens when I try to run my react server. A point to note is that it doesn't panic when there's a single pane.

![mosaic-panic](https://user-images.githubusercontent.com/44079328/102339263-eac24800-3fba-11eb-831f-f8e263939eff.gif)

Panic message: 
```rust
Originating Thread(s):
1. stream_terminal_bytes: AsyncTask
2. screen_thread: HandlePtyEvent

Error: thread 'screen' panicked at 'cursor out of bounds': src/terminal_pane/scroll.rs:380
   0: mosaic::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85:14
   6: core::option::expect_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226:5
   7: mosaic::terminal_pane::scroll::Scroll::add_character
   8: mosaic::terminal_pane::terminal_pane::TerminalPane::handle_event
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
  12: start_thread
  13: clone
```
Logfile: 
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5702106/mosaic-3.log)

**Comment by imsnif** [comment]
@kunalmohan - there are some compatibility fixes in main. Can you see if they maybe fix this for you?

**Comment by kunalmohan** [comment]
Yeah, it is fixed now. Thanks!
