### ISSUE TITLE
error thread screen panicked at cursor out of bounds when calling git log

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#113]
When calling both ```git log``` and ```git log --oneline```
```
Originating Thread(s):
1. stream_terminal_bytes: AsyncTask
2. screen_thread: HandlePtyEvent

Error: thread 'screen' panicked at 'cursor out of bounds': src/terminal_pane/scroll.rs:381
   0: mosaic::errors::handle_panic
             at src/errors.rs:15:21
   1: mosaic::start::{{closure}}
             at src/main.rs:187:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530:17
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437:5
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85:14
   5: core::option::expect_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1261:5
   6: core::option::Option<T>::expect
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:344:21
   7: mosaic::terminal_pane::scroll::Scroll::add_character
             at src/terminal_pane/scroll.rs:378:28
   8: <mosaic::terminal_pane::terminal_pane::TerminalPane as vte::Perform>::print
             at src/terminal_pane/terminal_pane.rs:362:9
   9: mosaic::terminal_pane::terminal_pane::TerminalPane::handle_event
             at src/terminal_pane/terminal_pane.rs:101:17
  10: mosaic::tab::Tab::handle_pty_event
             at src/tab.rs:376:13
  11: mosaic::start::{{closure}}
             at src/main.rs:276:29
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130:5
  13: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475:17
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318:9
  15: std::panicking::try::do_call
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:348:40
  16: __rust_try
  17: std::panicking::try
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:325:15
  18: std::panic::catch_unwind
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394:14
  19: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474:30
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233:5
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87:17
  22: start_thread
  23: clone

```
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5715684/mosaic-3.log)

**Comment by imsnif** [comment]
@denismaxim0v - could you please run it with `--debug` and include the mosaic-log?

**Comment by imsnif** [comment]
@denismaxim0v - I merged a fix for this in main just now. Could you please confirm it works for you?

**Comment by denismaxim0v** [comment]
> @denismaxim0v - I merged a fix for this in main just now. Could you please confirm it works for you?

Yup, it works
