### ISSUE TITLE
Compatibility: neovim commands

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#95]
Hitting backspace when trying to enter a command results in a crash.
Steps to reproduce:
 - Open neovim
 - start entering a command by pressing ```:```
 - hit backspace

```
Originating Thread(s):
1. stream_terminal_bytes: AsyncTask
2. screen_thread: HandlePtyEvent

Error: thread 'screen' panicked at 'swap_remove index (is 1) should be < len (is 1)': src/liballoc/vec.rs:975
   0: mosaic::errors::handle_panic
             at src/errors.rs:15:21
   1: mosaic::start::{{closure}}
             at src/main.rs:186:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530:17
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437:5
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85:14
   5: alloc::vec::Vec<T>::swap_remove::assert_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs:975:13
   6: alloc::vec::Vec<T>::swap_remove
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:980:13
   7: mosaic::terminal_pane::scroll::WrappedFragment::add_character
             at src/terminal_pane/scroll.rs:231:13
   8: mosaic::terminal_pane::scroll::Scroll::add_character
             at src/terminal_pane/scroll.rs:379:13
   9: <mosaic::terminal_pane::terminal_pane::TerminalPane as vte::Perform>::print
             at src/terminal_pane/terminal_pane.rs:362:9
  10: mosaic::terminal_pane::terminal_pane::TerminalPane::handle_event
             at src/terminal_pane/terminal_pane.rs:101:17
  11: mosaic::screen::Screen::handle_pty_event
             at src/screen.rs:395:13
  12: mosaic::start::{{closure}}
             at src/main.rs:248:29
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130:5
  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475:17
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318:9
  16: std::panicking::try::do_call
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:348:40
  17: __rust_try
  18: std::panicking::try
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:325:15
  19: std::panic::catch_unwind
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394:14
  20: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474:30
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/denis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233:5
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87:17
  23: start_thread
  24: clone

```

**Comment by imsnif** [comment]
Hey @denismaxim0v, I think this bug is fixed in main too. Can you please try?

**Comment by denismaxim0v** [comment]
Everything works really good

**Comment by imsnif** [comment]
> Everything works really good

Awesome :) So also: https://github.com/mosaic-org/mosaic/issues/94?
